# Generated by Django 4.2.11 on 2024-04-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expose_patient_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla_test',
        ),
    ]
